version: "3.9"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-dev
    # restart: unless-stopped

    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "admin@supersecret123"
      MSSQL_PID: "Developer"

    ports:
      - "1433:1433"

    volumes:
      - mssql_data:/var/opt/mssql

    healthcheck:
      test: [
        "CMD-SHELL",
        "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P admin@supersecret123 -Q 'SELECT 1'"
      ]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mssql_data:
